language: rust
cache: cargo

os:
  - linux
  - osx

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  include:
    - rust: nightly
      script: cargo build --features "clippy"
      env: NAME=clippy
