language: rust

cache: cargo

rust:
  - stable
  - beta
  - nightly

script:
  - cargo test --verbose
  - |
    if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
      cargo build --features "clippy"
    fi
