[package]
name = "veloce"
version = "0.1.0"
authors = ["d-dorazio <d.dorazio96@gmail.com>"]

[dependencies]
# hyper is required only for the header! macro
hyper = "0.11"
reqwest = "0.8"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
structopt = "0.2"
